create table
  public.subscriptions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    email text null,
    status text null,
    constraint subscriptions_pkey primary key (id)
  ) tablespace pg_default;