CREATE TABLE public.parentPayloads (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title character varying not null,
    thumbnail character varying not null,
    -- created_by uuid not null,
    description character varying not null,
    royalties character varying not null,
    location character varying null,
    status character varying null,
    mainFile character varying not null,
    constraint parentPayloads_pkey primary key (id)
) tablespace pg_default;

CREATE TABLE public.collections (
    id bigint generated by default as identity,
    creator uuid not null references profiles(id) on delete cascade,  -- Foreign key to profiles table
    name character varying not null,
    description character varying not null,
    cover_image character varying not null,
    constraint collections_pkey primary key (id)
) tablespace pg_default;

create table
  public.childassets (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title character varying not null,
    thumbnail character varying not null,
    mainmedia character varying not null,
    mainfile character varying not null,
    description character varying not null,
    units character varying not null,
    collection_id bigint null,
    parent_payload_id bigint not null,
    author uuid null,
    constraint childassets_pkey primary key (id),
    constraint childassets_author_fkey foreign key (author) references profiles (id),
    constraint fk_collection foreign key (collection_id) references collections (id) on delete set null,
    constraint fk_parent_payload foreign key (parent_payload_id) references parentpayloads (id) on delete cascade
  ) tablespace pg_default;